project:
  type: website
  output-dir: docs
website:
  title: "Rajiv's blog about data science"
  site-url: https://rajivsam.github.io/r2ds-blog/
  navbar:
    right:
      - about.qmd
      - icon: file-person-fill
        href: https://www.r2-ds.com
      - icon: file-earmark-person
        href: https://rajivsam.github.io/
      - icon: rss
        href: index.xml  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



