project:
  type: website
  output-dir: docs
website:
  title: "r2ds-blog"
  navbar:
    right:
      - about.qmd
      - icon: file-person-fill
        href: https://www.r2-ds.com
      - icon: file-earmark-person
        href: https://rajivsam.github.io/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



